version: "3"
services:

  jaeger:
    image: jaegertracing/example-hotrod:latest
    command: all
    environment:
      - JAEGER_AGENT_HOST=jaeger-agent
      - JAEGER_AGENT_PORT=6831
    ports:
      - "8080-8083:8080-8083"
    depends_on:
      - jaeger-agent

  jaeger-agent:
    image: jaegertracing/jaeger-agent:latest
    environment:
      - REPORTER_GRPC_HOST_PORT=otel-collector:14250
    ports:
      - "6831:6831/udp"
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib-dev:latest
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "14250" #jaeger
      # - "55678" # OpenCensus receiver
