receivers:
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250

exporters:
  otlp:
    endpoint: "otel-collector:55678"
    insecure: true
  logging:
    loglevel: debug

processors:
  batch:
  queued_retry:

extensions:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679
  health_check:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [jaeger]
      exporters: [otlp, logging]
      processors: [batch, queued_retry]
