receivers:
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250

exporters:
  logging:

  elastic:
    apm_server_url: "{URL}"
    secret_token: "{TOKEN}"

processors:
  batch: 1s
  queued_retry: 1024

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [jaeger]
      exporters: [elastic, logging]
      processors: [batch, queued_retry]
